version: '3.8'

services:
  ocr-app:
    build: .
    container_name: ocr-app
    ports:
      - "9001:9001"
    volumes:
      - .:/OCR
      - ocr_models:/models/ocr
      - /OCR/__pycache__
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

volumes:
  ocr-app:
